CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL DEFAULT 'ESTUDIANTE',
    cuenta_verificada BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_usuario_rol
        CHECK (rol IN ('ESTUDIANTE', 'ADMIN'))
);

CREATE TABLE estudiante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    edad SMALLINT,
    grado_escolar SMALLINT,

    CONSTRAINT fk_estudiante_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id),

    CONSTRAINT chk_estudiante_edad
        CHECK (edad IS NULL OR edad BETWEEN 10 AND 18),

    CONSTRAINT chk_estudiante_grado
        CHECK (grado_escolar IS NULL OR grado_escolar BETWEEN 1 AND 3)
);